#!/usr/bin/env python3
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TICKET_DIR = ROOT / "maintenance" / "tickets"
INDEX = ROOT / "maintenance" / "TICKET_INDEX.md"
TMP_PATTERNS = ("gpt-api*.md", "coding-agent*.md", "openapi*.md")
FRONT_MATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.S)


def parse_front_matter(text: str) -> dict[str, str]:
    match = FRONT_MATTER_RE.match(text)
    if not match:
        return {}
    data: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip().strip('"')
    return data


def first_heading(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def infer_area(name: str, text: str) -> str:
    haystack = f"{name} {text[:1000]}".lower()
    if "openapi" in haystack or "schema" in haystack:
        return "schema"
    if "endpoint" in haystack or "404" in haystack or "route" in haystack:
        return "endpoint"
    if "timeout" in haystack or "hang" in haystack or "production" in haystack:
        return "runtime"
    if "git" in haystack or "push" in haystack or "remote" in haystack:
        return "release"
    if "command_too_long" in haystack or "command too long" in haystack:
        return "tooling"
    return "maintenance"


def infer_severity(name: str, text: str) -> str:
    haystack = f"{name} {text[:1000]}".lower()
    if any(word in haystack for word in ["production", "hang", "timeout", "403", "404", "blocked", "blocker"]):
        return "high"
    if any(word in haystack for word in ["validator", "schema", "command_too_long", "dirty"]):
        return "medium"
    return "low"


def import_tmp_tickets() -> list[Path]:
    TICKET_DIR.mkdir(parents=True, exist_ok=True)
    imported: list[Path] = []
    for pattern in TMP_PATTERNS:
        for src in sorted(Path("/tmp").glob(pattern)):
            dest = TICKET_DIR / src.name
            if dest.exists():
                imported.append(dest)
                continue
            text = src.read_text(encoding="utf-8", errors="replace")
            ticket_id = src.stem
            area = infer_area(src.name, text)
            severity = infer_severity(src.name, text)
            front_matter = (
                "---\n"
                f"id: {ticket_id}\n"
                "status: open\n"
                f"severity: {severity}\n"
                f"area: {area}\n"
                f"created: {datetime.now(timezone.utc).date().isoformat()}\n"
                "resolved:\n"
                "---\n\n"
            )
            dest.write_text(text if FRONT_MATTER_RE.match(text) else front_matter + text, encoding="utf-8")
            imported.append(dest)
    return imported


def build_index() -> str:
    rows: list[tuple[str, str, str, str, str, str]] = []
    for path in sorted(TICKET_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8", errors="replace")
        meta = parse_front_matter(text)
        ticket_id = meta.get("id", path.stem)
        status = meta.get("status", "unknown")
        severity = meta.get("severity", "unknown")
        area = meta.get("area", infer_area(path.name, text))
        title = first_heading(text, path.stem)
        rows.append((area, severity, status, ticket_id, title, path.name))
    lines = [
        "# Maintainer Ticket Index",
        "",
        "Generated by: `scripts/ticket_index.py`",
        "",
        f"Ticket count: {len(rows)}",
        "",
        "| Area | Severity | Status | ID | Title | File |",
        "|---|---|---|---|---|---|",
    ]
    for area, severity, status, ticket_id, title, filename in sorted(rows):
        safe_title = title.replace("|", "/")
        lines.append(f"| {area} | {severity} | {status} | `{ticket_id}` | {safe_title} | `maintenance/tickets/{filename}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    imported = import_tmp_tickets()
    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(build_index(), encoding="utf-8")
    print(f"tickets_imported_or_present={len(imported)}")
    print(f"index={INDEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
